# serverless.yml
service:
  name: lambdaPublishSns 

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-2

environment:
  myTopicName: "arn:aws:sns:us-east-2:160116285639:PublishToSNS"

custom:
  serverless-offline-sns:
    port: 4002  
    debug: true

functions:
  publishSns:
    handler: handler.publishSns
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
      - Action:
          - sns: Publish
          - sns: Subscribe
      - Resource: 
          - Ref: "arn:aws:sns:us-east-2:160116285639:PublishToSNS" 
    events:
      - http:
          method: get
          path: publishSns
